### PR TITLE
Update CountryData.kt

### PR DESCRIPTION
**Pull request by GuilhE**
Adds helper function to list all countries

### CODE REVIEW

**Comment by ParveshSandila** [comment]
I have merged your pull request. But I Believe, it is not a good idea to expose the object of CountryData outside the package as it contains references to drawable and strings. instead of this, a better solution could be to create a particular data class and return limited data as a return. because in future there could be possible other data in CountryData lists. I possibly work on this. Thank you so much for your valuable contributions.

**Comment by GuilhE** [comment]
> I have merged your pull request. But I Believe, it is not a good idea to expose the object of CountryData outside the package as it contains references to drawable and strings. instead of this, a better solution could be to create a particular data class and return limited data as a return. because in future there could be possible other data in CountryData lists. I possibly work on this. Thank you so much for your valuable contributions.

It's a good point, but I believe the information exposed is not critical. For instance, I can leverage the fact that your lib handles the values-x and drawbles if I need access to it in my app. Otherwise I would have to replicate that on my end. 
We can add helper functions to retrieve the name/image instead of the resource, true, but would you want your lib handling the Context instance to allow 'getString()' or 'getDrawable()'? We can ask it as a parameter also but that's not elegant. Let me see what I can think of tomorrow ;)

**Comment by GuilhE** [comment]
This is one approach I can think of:
```
sealed class CountryData(
    val countryNameResId: Int,
    val flagResId: Int,
    val countryCodeWithPrefix: String,
    val countryCodeWithoutPrefix: String,
    val iso2: String,
    val iso3Code: String
) {
    companion object Factory {
        private object AfghanistanResources {
            val countryNameResId = R.string.afghanistan
            val flagResId = R.drawable.afghanistan_flag
        }

        object Afghanistan : CountryData(
            AfghanistanResources.countryNameResId,
            AfghanistanResources.flagResId,
            "+93",
            "93",
            "AF",
            "AFG"
        )
    }
}
```
It will hide the implementation details. Exposing the resources can lead to tighter coupling between the callers and the resources themselves. If the callers directly depend on the specific resources, any changes to the resource names, IDs, or types would require updating all the callers accordingly.

And we could go one step further also:
```
sealed class CountryData(
    val countryNameResId: Int,
    val flagResId: Int,
    val countryCode: String,
    val iso2Code: String,
    val iso3Code: String
) {

   val countryCodeWithPrefix: String = "+$countryCode"
    ...
}
```

Finally, as a user who uses this lib, if you find helpful you can do something like:

```
typealias Afghanistan = CountryData.Factory.Afghanistan
```

**Comment by ParveshSandila** [comment]
Really sorry I got busy so that's why I couldn't reply. I love this approach but my concern is if we expose our resource Ids to users will they be able to use them directly e.g. stringResource(counrtyCode.countryNameResId)? Or we can return a string as a country name and a flag as a bitmap. Please reply to me with your opinion. If you believe that sending resource ids will work. we will go with this approach.

**Comment by GuilhE** [comment]
I see no problem in exposing this resources honestly. What practical concerns do you have in mind? I believe the library should not provide a bitmap or a final string because that means - in the case of the string -, you'll lose resource resolution. Passing the `context` to library is not elegant either. Also you'll force the user using bitmaps (or converting back to resources) in places that don't accept bitmap.

And actually you always have access to a module's resources, try `<package-name>.R.drawables`... so they're already exposed. Example: `import com.google.android.material.R.drawable.notification_bg`

**Comment by GuilhE** [comment]
@ParveshSandila any update?

**Pull request merged**
